services:
  server:
    build:
      dockerfile: ./build/docker/Dockerfile
      context: ./server
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:50051", "grpc.health.v1.Health.Check"]
      interval: 10s
      timeout: 10s
      retries: 3
  proxy:
    container_name: envoy-proxy
    image: envoyproxy/envoy:distroless-v1.27.0
    ports:
      - "${PROXY_PORT}:10000"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
